#!/usr/bin/env python3
"""Extract periodic screenshots from the camera portion of a magnet overlay video.

The overlay videos generated by ``overlay_eval_video_with_magnet.py`` place the
camera image on the left and the magnetic visualization panel on the right.
This script removes that panel before writing screenshots.
"""

import argparse
from pathlib import Path

import cv2


def parse_args():
    parser = argparse.ArgumentParser(
        description="Save periodic screenshots from the non-magnet part of a video."
    )
    parser.add_argument("--video", required=True, help="Input magnet-overlay video")
    parser.add_argument(
        "--output-dir",
        default=None,
        help=(
            "Directory for PNG screenshots. Defaults to <video>_frames next to "
            "the input video."
        ),
    )
    parser.add_argument(
        "--frame-interval",
        type=int,
        default=30,
        help="Save one image every N frames, including frame 0 (default: 30).",
    )
    parser.add_argument(
        "--magnet-panel-width",
        type=int,
        default=620,
        help="Number of pixels to remove from the right side (default: 620).",
    )
    parser.add_argument(
        "--start-frame",
        type=int,
        default=0,
        help="First frame index to consider (default: 0).",
    )
    return parser.parse_args()


def extract_camera_frames(
    video_path,
    output_dir=None,
    frame_interval=30,
    magnet_panel_width=620,
    start_frame=0,
):
    """Extract camera-only frames and return the written paths."""
    video_path = Path(video_path).expanduser()
    if not video_path.is_file():
        raise FileNotFoundError(f"Input video does not exist: {video_path}")
    frame_interval = int(frame_interval)
    magnet_panel_width = int(magnet_panel_width)
    start_frame = int(start_frame)
    if frame_interval <= 0:
        raise ValueError(f"frame_interval must be positive, got {frame_interval}")
    if magnet_panel_width < 0:
        raise ValueError(
            f"magnet_panel_width must be non-negative, got {magnet_panel_width}"
        )
    if start_frame < 0:
        raise ValueError(f"start_frame must be non-negative, got {start_frame}")

    if output_dir is None:
        output_dir = video_path.with_name(f"{video_path.stem}_frames")
    output_dir = Path(output_dir).expanduser()
    output_dir.mkdir(parents=True, exist_ok=True)

    capture = cv2.VideoCapture(str(video_path))
    if not capture.isOpened():
        raise RuntimeError(f"Could not open input video: {video_path}")

    written = []
    frame_idx = 0
    try:
        while True:
            ok, frame = capture.read()
            if not ok:
                break
            if frame_idx >= start_frame and (frame_idx - start_frame) % frame_interval == 0:
                height, width = frame.shape[:2]
                camera_width = width - magnet_panel_width
                if camera_width <= 0:
                    raise ValueError(
                        "magnet_panel_width removes the complete video frame: "
                        f"video_width={width}, magnet_panel_width={magnet_panel_width}"
                    )
                camera_frame = frame[:, :camera_width]
                output_path = output_dir / f"frame_{frame_idx:06d}.png"
                if not cv2.imwrite(str(output_path), camera_frame):
                    raise RuntimeError(f"Could not write screenshot: {output_path}")
                written.append(output_path)
            frame_idx += 1
    finally:
        capture.release()

    return written, frame_idx


def main():
    args = parse_args()
    written, frame_count = extract_camera_frames(
        video_path=args.video,
        output_dir=args.output_dir,
        frame_interval=args.frame_interval,
        magnet_panel_width=args.magnet_panel_width,
        start_frame=args.start_frame,
    )
    output_dir = Path(args.output_dir).expanduser() if args.output_dir else Path(args.video).expanduser().with_name(f"{Path(args.video).stem}_frames")
    print(
        f"Read {frame_count} frames and wrote {len(written)} camera-only screenshots "
        f"to {output_dir} (every {args.frame_interval} frames, "
        f"removed right panel width={args.magnet_panel_width}px)."
    )


if __name__ == "__main__":
    main()
